version: '3'
# https://dev-pages.info/how-to-run-spring-boot-and-mongodb-in-docker-using-docker-compose/
services: 
    springboot:
        build: api/
        restart: always
        container_name: springboot
        ports: 
            - 8080:8080
        depends_on: 
            - mongo
    mongo:
        image: mongo
        container_name: api-mongo
        volumes: 
            - $HOME/data/db:/data/db
            - $HOME/data/bkp:/data/bkp
        restart: always